alias cls="clear"
alias ra="ranger"
alias vim="nvim"
alias bashrc="nvim ~/config/bash/my.bashrc"
alias bashrcs="source ~/config/bash/my.bashrc"
alias nvimrc="vim ~/.config/nvim/init.vim"
alias zshrc="vim ~/.zshrc"
alias zshrcs="source ~/.zshrc"
